services:
  broadband-speed-monitor:
    image: broadband-speed-monitor
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../.env
    network_mode: "host"
    working_dir: /app